### ISSUE TITLE
Issue with onValueSelected

### ISSUE THREAD

**Issue by cayasso** [tiqtech/enyo-extras#14]
onValueSelected will never fire, because this.doValueSelected are not being called, just add something like this to the itemSelected method to fix.

Replace this:

``` javascript
itemSelected: function(source, event) {
        this.inputField.setValue(event.content);
}
```

with this:

``` javascript
itemSelected: function(source, event) {
        this.inputField.setValue(event.content);
        this.doValueSelected({ value: event.content });
}
```

Best,
JB

**Comment by ryanjduffy** [comment]
Assuming this is tied to the AutoCompleteInputDecorator (based on the code you included)? It doesn't have an onValueSelected event so i'm not sure what you're expecting to trigger.

**Comment by cayasso** [comment]
Sorry, yes it's related to AutoCompleteInputDecorator, the code is a fraction of your code, yo have two events in the source starting at line #15:

events.onInputChanged and events.onValueSelected, this last one never get triggered.

Sorry for the briefness, I am responding from my phone.
Best,
JB

**Comment by ryanjduffy** [comment]
Should be fixed now. Not sure why I didn't see that event the first time I looked. Thanks!

**Comment by cayasso** [comment]
Sure np!!

Best,
JB

On Mon, Oct 29, 2012 at 1:51 PM, Ryan Duffy notifications@github.comwrote:

> Should be fixed now. Not sure why I didn't see that event the first time I
> looked. Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/tiqtech/enyo-extras/issues/14#issuecomment-9882823.

## 

J.B.
